// <auto-generated />
using System;
using HighSchool_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighSchool_Management_System.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250103054627_AddUniqueConstraintToSchoolClass")]
    partial class AddUniqueConstraintToSchoolClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HighSchool_Management_System.Model.SchoolClass", b =>
                {
                    b.Property<int>("SchoolClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FormTeacherId")
                        .HasColumnType("int");

                    b.HasKey("SchoolClassId");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.HasIndex("FormTeacherId")
                        .IsUnique()
                        .HasFilter("[FormTeacherId] IS NOT NULL");

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SchoolClassId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.SchoolClass", b =>
                {
                    b.HasOne("HighSchool_Management_System.Model.Teacher", "FormTeacher")
                        .WithOne("FormClass")
                        .HasForeignKey("HighSchool_Management_System.Model.SchoolClass", "FormTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FormTeacher");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.Student", b =>
                {
                    b.HasOne("HighSchool_Management_System.Model.SchoolClass", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId");

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.SchoolClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("HighSchool_Management_System.Model.Teacher", b =>
                {
                    b.Navigation("FormClass");
                });
#pragma warning restore 612, 618
        }
    }
}
